CREATE TABLE cobrancas_pix_vistoria (
    id CHAR(36) NOT NULL PRIMARY KEY,
    pagamento_vistoria_id CHAR(36) NOT NULL,
    valor DECIMAL(12,2) NOT NULL,
    txid VARCHAR(35) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status INT NOT NULL,
    expiracao_segundos INT NOT NULL,
    provider_criado_em DATETIME(6) NULL,
    vence_em DATETIME(6) NULL,
    confirmado_em DATETIME(6) NULL,
    end_to_end_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    revisao INT NULL,
    codigo VARCHAR(40) NULL,
    lease_id CHAR(36) NULL,
    lease_expira_em DATETIME(6) NULL,
    proxima_consulta_em DATETIME(6) NOT NULL,
    remocao_solicitada BOOLEAN NOT NULL DEFAULT FALSE,
    pix_ciphertext VARBINARY(8192) NULL,
    pix_nonce BINARY(12) NULL,
    pix_tag BINARY(16) NULL,
    encryption_version INT NULL,
    link_hash BINARY(32) NULL,
    link_expira_em DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    pagamento_nao_terminal CHAR(36) GENERATED ALWAYS AS
        (CASE WHEN status NOT IN (5,6,8,9) THEN pagamento_vistoria_id ELSE NULL END) STORED,
    CONSTRAINT fk_cobranca_pagamento FOREIGN KEY (pagamento_vistoria_id) REFERENCES pagamentos_vistoria(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uq_cobranca_txid UNIQUE (txid),
    CONSTRAINT uq_cobranca_e2e UNIQUE (end_to_end_id),
    CONSTRAINT uq_cobranca_aberta UNIQUE (pagamento_nao_terminal),
    CONSTRAINT uq_cobranca_link UNIQUE (link_hash),
    CONSTRAINT ck_cobranca_status CHECK (status BETWEEN 0 AND 10),
    CONSTRAINT ck_cobranca_valor CHECK (valor > 0),
    CONSTRAINT ck_cobranca_txid CHECK (txid REGEXP '^[a-zA-Z0-9]{26,35}$'),
    CONSTRAINT ck_cobranca_prazo CHECK (expiracao_segundos BETWEEN 60 AND 86400),
    CONSTRAINT ck_cobranca_lease CHECK ((lease_id IS NULL AND lease_expira_em IS NULL) OR (lease_id IS NOT NULL AND lease_expira_em IS NOT NULL)),
    CONSTRAINT ck_cobranca_link CHECK ((link_hash IS NULL AND link_expira_em IS NULL) OR (link_hash IS NOT NULL AND link_expira_em IS NOT NULL)),
    CONSTRAINT ck_cobranca_crypto CHECK ((pix_ciphertext IS NULL AND pix_nonce IS NULL AND pix_tag IS NULL AND encryption_version IS NULL) OR (pix_ciphertext IS NOT NULL AND pix_nonce IS NOT NULL AND pix_tag IS NOT NULL AND encryption_version IS NOT NULL AND encryption_version=1)),
    INDEX ix_cobranca_candidatos(status, proxima_consulta_em, lease_expira_em, id),
    INDEX ix_cobranca_pagamento(pagamento_vistoria_id, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE recebimentos_pix_inbox (
    id CHAR(36) NOT NULL PRIMARY KEY,
    evento_hash BINARY(32) NOT NULL,
    end_to_end_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    txid VARCHAR(35) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    valor DECIMAL(12,2) NOT NULL,
    horario DATETIME(6) NOT NULL,
    status INT NOT NULL DEFAULT 0,
    codigo VARCHAR(40) NULL,
    lease_id CHAR(36) NULL,
    lease_expira_em DATETIME(6) NULL,
    proxima_consulta_em DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT uq_recebimento_evento UNIQUE(evento_hash),
    CONSTRAINT ck_recebimento_status CHECK(status IN (0,1,2,3)),
    CONSTRAINT ck_recebimento_valor CHECK(valor>0),
    CONSTRAINT ck_recebimento_lease CHECK ((lease_id IS NULL AND lease_expira_em IS NULL) OR (lease_id IS NOT NULL AND lease_expira_em IS NOT NULL)),
    INDEX ix_recebimento_candidatos(status, proxima_consulta_em, lease_expira_em, id),
    INDEX ix_recebimento_txid(txid),
    INDEX ix_recebimento_e2e(end_to_end_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE operacoes_cobranca_pix (
    id CHAR(36) NOT NULL PRIMARY KEY,
    cobranca_id CHAR(36) NOT NULL,
    inbox_id CHAR(36) NULL,
    tipo INT NOT NULL,
    codigo VARCHAR(40) NULL,
    started_at DATETIME(6) NOT NULL,
    finished_at DATETIME(6) NULL,
    CONSTRAINT fk_operacao_cobranca FOREIGN KEY(cobranca_id) REFERENCES cobrancas_pix_vistoria(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_operacao_inbox FOREIGN KEY(inbox_id) REFERENCES recebimentos_pix_inbox(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_operacao_cobranca_tipo CHECK(tipo BETWEEN 0 AND 4),
    INDEX ix_operacao_cobranca(cobranca_id, started_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
